# Generated by Django 4.1 on 2022-09-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_options',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
