# Generated by Django 4.1 on 2022-09-03 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_author_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('018a00b3-afc2-46e6-9758-a559d3716c25'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
