# Generated by Django 4.1 on 2022-09-03 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_identifier_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('ea26184d-2620-4e68-834e-8927c842def3'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('1b6891f5-9082-48e5-94f7-ff2e1bcf2f79'), null=True),
        ),
    ]
