# Generated by Django 4.1 on 2022-09-05 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('412fcc60-c1fc-434c-8b04-1950cf9510f4'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('380d8444-d4e3-47db-a70e-5262ad656c30'), null=True),
        ),
    ]
