# Generated by Django 4.1 on 2022-09-05 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('16ac5b80-5d35-406f-8b10-70be4b959cc6'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('08779d31-4f3c-4c18-aeeb-3a33865204d2'), null=True),
        ),
    ]
