# Generated by Django 4.1 on 2022-09-05 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('4a66ae25-896e-4427-9d45-41a2872de2db'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('2d1e85a3-bab7-4bc5-a926-cdfe81a49af6'), null=True),
        ),
    ]
