# Generated by Django 4.1 on 2022-09-05 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('28c3dd51-5ba8-4ed4-a465-b55f340800ef'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('5c27c809-74a3-4f81-95b5-25d685f63554'), null=True),
        ),
    ]
