# Generated by Django 4.1 on 2022-09-05 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_options_alter_option_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('32cb4caa-c0f0-43e5-a661-15b16735857d'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('4d69e527-e8a7-4983-b009-5024d2d1f484'), null=True),
        ),
    ]
