# Generated by Django 4.1 on 2022-09-05 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('1ae16ae5-d545-48e7-b898-172d93bfb36f'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('4264e810-58aa-4ef5-a245-3357e63a7df1'), null=True),
        ),
    ]
