# Generated by Django 4.1 on 2022-09-05 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('eeca9b51-4c6c-4811-97bb-6f0ec62361e4'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7d854f47-cc3e-46e0-a045-4c045cf31368'), null=True),
        ),
    ]
