# Generated by Django 4.1 on 2022-09-05 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('dd5ef009-8b73-4c7d-a267-a5495aae6b53'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('4c567d24-7cf9-4c06-b9c4-43fc27e0138f'), null=True),
        ),
    ]
