# Generated by Django 4.1 on 2022-09-05 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('0ea3cadc-c120-4b88-b00f-00de81dc89d5'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('00b5557d-cdd2-433f-b09a-3bdc9283bdb5'), null=True),
        ),
    ]
