# Generated by Django 4.1 on 2022-09-05 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('7cb67638-2c29-40f7-ac24-54d282febe04'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('1cda5330-15af-40a8-9c0a-60b3a9000d52'), null=True),
        ),
    ]
