# Generated by Django 4.1 on 2022-09-05 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('a600eda0-83e8-4421-bbd9-1484c3d1b1fc'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('9d332ad1-e0e5-4aeb-9fda-230e1e37b8c4'), null=True),
        ),
    ]
