# Generated by Django 4.1 on 2022-09-05 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('6bd0799d-a107-467d-b931-110771a06cf7'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('4a14ed02-0cf6-4cbc-9817-36f75798f7aa'), null=True),
        ),
    ]
