# Generated by Django 4.1 on 2022-09-05 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('6ed5bf16-c406-44cf-8f5f-b81bd04fac3c'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('676d3b41-da17-4ad2-a83c-f62a7608be34'), null=True),
        ),
    ]
