# Generated by Django 4.1 on 2022-09-05 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('b859a26e-b364-4c06-9e17-41a6fb594858'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('8d7243e1-9974-44dc-a22e-d828f2a5361c'), null=True),
        ),
    ]
