# Generated by Django 4.1.3 on 2022-11-04 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_option_identifier_alter_poll_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='identifier',
            field=models.UUIDField(blank=True, default=uuid.UUID('e34e33ca-0efb-4bc2-84bc-137c3c552696'), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(default=uuid.UUID('a5db1be1-f6d2-4d28-94c3-86947d46eced'), editable=False),
        ),
    ]
